package space.zenithw.app

import android.content.Context
import android.content.res.Configuration
import android.view.ContextThemeWrapper
import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

val LocalAppContext=staticCompositionLocalOf<Context> { error("App language context missing") }

object AppLanguage {
    val choices=listOf("tr" to "Türkçe","en" to "English","de" to "Deutsch","fr" to "Français","ru" to "Русский")
    fun valid(tag: String)=tag.takeIf { value -> choices.any { it.first==value } } ?: "tr"
    fun context(base: Context,tag: String=LocalStore(base).language): Context {
        val configuration=Configuration(base.resources.configuration)
        configuration.setLocale(Locale.forLanguageTag(valid(tag)))
        return ContextThemeWrapper(base,base.theme).apply { applyOverrideConfiguration(configuration) }
    }
    // Older download records store Turkish status text. Translate those app-owned messages
    // at display time, so changing language also updates history without rewriting user data.
    private val legacy=mapOf(
        "Yapıştır" to R.string.paste,
        "İndir" to R.string.download,
        "Dosyalar" to R.string.files,
        "Ayarlar" to R.string.settings,
        "Dil" to R.string.language,
        "Bağlantıyı temizle" to R.string.clear_link,
        "Henüz dosya yok" to R.string.empty_files,
        "İptal et" to R.string.cancel_download,
        "Aç" to R.string.open,
        "Paylaş" to R.string.share,
        "Tekrar dene" to R.string.retry,
        "İndirme motoru" to R.string.engine,
        "yt-dlp hazırlanıyor" to R.string.preparing_engine,
        "Otomatik güncelle" to R.string.auto_update,
        "Kararlı" to R.string.stable,
        "Kontrol ediliyor" to R.string.checking,
        "Şimdi kontrol et" to R.string.check_now,
        "Bağlı oturumlar" to R.string.sessions,
        "Dosyaları paylaş" to R.string.share_files,
        "Dosyayı açabilecek bir uygulama bulunamadı." to R.string.no_opener,
        "Video" to R.string.video,
        "Ses" to R.string.audio,
        "Altyazı" to R.string.subtitle,
        "Medya hazır" to R.string.media_ready,
        "Pencereyi kapat" to R.string.close_window,
        "Kalite" to R.string.quality,
        "En iyi" to R.string.best,
        "Dosya biçimi" to R.string.file_format,
        "Ses biçimi" to R.string.audio_format,
        "Kapak görseli" to R.string.thumbnail,
        "Desteklenen biçimlerde dosyaya gömülür." to R.string.thumbnail_hint,
        "Dosya içeriği" to R.string.file_content,
        "Medya bilgileri, kapak ve codec" to R.string.file_content_hint,
        "Medya bilgilerini göm" to R.string.embed_metadata,
        "Bölümleri göm" to R.string.embed_chapters,
        "Yükleyici bilgisini ekle" to R.string.embed_uploader,
        "Kapağı ayrıca kaydet" to R.string.save_thumbnail,
        "Video codec" to R.string.video_codec,
        "Otomatik" to R.string.automatic,
        "Bazı codec ve dosya biçimleri birlikte kullanılamayabilir." to R.string.codec_hint,
        "Sponsor bölümlerini kaldır" to R.string.remove_sponsors,
        "SponsorBlock verisi varsa uygulanır." to R.string.sponsor_hint,
        "Kategoriler" to R.string.categories,
        "Altyazılar" to R.string.subtitles,
        "Dil ve dosya biçimi" to R.string.subtitle_settings,
        "İstersen ekle" to R.string.optional_add,
        "Altyazıları indir" to R.string.download_subtitles,
        "Otomatik altyazıları da al" to R.string.auto_subtitles,
        "Diller · tr.*,en.*" to R.string.subtitle_languages,
        "Altyazıyı videoya göm" to R.string.embed_subtitles,
        "Bağlantı ve hız" to R.string.connection_speed,
        "Aria2c açık" to R.string.aria_enabled,
        "Standart indirme" to R.string.standard_download,
        "Aria2c kullan" to R.string.use_aria,
        "Desteklenen bağlantılarda; hata olursa normal motor denenir." to R.string.aria_hint,
        "Sunucu başına bağlantı" to R.string.server_connections,
        "Hız sınırı · KB/sn, 0 = sınırsız" to R.string.speed_limit,
        "Paralel parçalar" to R.string.fragments,
        "Tekrar deneme sayısı" to R.string.retries,
        "Parça tekrar denemeleri" to R.string.fragment_retries,
        "Proxy · isteğe bağlı" to R.string.proxy,
        "User-Agent · isteğe bağlı" to R.string.user_agent,
        "Yalnızca ölçülmeyen ağ" to R.string.unmetered,
        "Wi-Fi veya başka bir ölçülmeyen bağlantıyı bekler." to R.string.unmetered_hint,
        "Diğer seçenekler" to R.string.other_options,
        "Oynatma listesi, zamanlama ve dosya adı" to R.string.other_options_hint,
        "Oynatma listesini indir" to R.string.playlist,
        "Liste öğeleri · 1:5,8" to R.string.playlist_items,
        "Dosya adı şablonu" to R.string.filename,
        "Özel azami kalite · 0 = en iyi" to R.string.max_quality,
        "Format kimliği · isteğe bağlı" to R.string.format_id,
        "İndirmeyi zamanla" to R.string.schedule_download,
        "Zamanlamayı kaldır" to R.string.remove_schedule,
        "Zamanla" to R.string.schedule,
        "İndirmeyi başlat" to R.string.start_download,
        "Oturumların." to R.string.your_sessions,
        "Giriş isteyen içerikler için bir oturum seç." to R.string.session_hint,
        "Oturumsuz devam et" to R.string.no_session,
        "✓ Oturumsuz devam et" to R.string.no_session_selected,
        "Oturumu sil" to R.string.delete_session,
        "Yeni oturum bağla" to R.string.new_session,
        "Cookie dosyası içe aktar" to R.string.import_cookies,
        "Oturum bilgileri bu cihazda şifreli saklanır ve yalnızca seçtiğin indirmede kullanılır. Uygulama içi girişe izin vermeyen sitelerde Netscape cookie dosyası kullanabilirsin." to R.string.session_privacy,
        "Oturum bağla" to R.string.connect_session,
        "Siteyi aç, hesabına giriş yap ve oturumu kaydet." to R.string.open_login_hint,
        "Site adresi" to R.string.site_address,
        "Güvenli bir https:// adresi gir." to R.string.secure_url,
        "Adresi kontrol et." to R.string.check_address,
        "Siteyi aç" to R.string.open_site,
        "Vazgeç" to R.string.cancel,
        "Sitenin güvenli bağlantısı doğrulanamadı." to R.string.ssl_error,
        "Geri" to R.string.back,
        "Varsayılan tarayıcıda aç" to R.string.open_browser,
        "Giriş yaptıktan sonra kaydet. Uygulama içi giriş engellenirse cookie dosyası içe aktarabilirsin." to R.string.save_login_hint,
        "Site adresi alınamadı" to R.string.missing_site,
        "Oturum kaydedilemedi." to R.string.session_save_error,
        "Kaydediliyor" to R.string.saving,
        "Bu oturumu kaydet" to R.string.save_session,
        "Cookie dosyası çok büyük." to R.string.cookie_large,
        "Dosya açılamadı." to R.string.file_open_error,
        "Cookie dosyası şifreli olarak kaydedildi." to R.string.cookie_saved,
        "Cookie dosyası okunamadı. Netscape biçiminde bir dosya seç." to R.string.cookie_read_error,
        "Bağlantıyı kontrol et." to R.string.check_link,
        "Medya bilgisi alınamadı. Paylaşım bağlantısını kontrol et; gerekirse bir oturum bağla." to R.string.media_error,
        "Sırada" to R.string.queued,
        "Zamanlandı" to R.string.scheduled,
        "İndirme sıraya eklendi." to R.string.download_queued,
        "Geçerli bir paylaşım bağlantısı gir." to R.string.valid_link,
        "Geçerli bir site adresi gir." to R.string.valid_site,
        "Bağlantıda geçersiz karakter var." to R.string.invalid_link,
        "Bu siteden henüz oturum bilgisi alınamadı." to R.string.missing_cookie,
        "Seçili oturum bulunamadı; yeniden bağlan." to R.string.missing_session,
        "Bağlantı ve medya hazırlanıyor" to R.string.preparing_media,
        "Cihaza kaydediliyor" to R.string.saving_device,
        "Kaydedildi" to R.string.saved,
        "Kaydedildi · açıklamayı kontrol et" to R.string.saved_notes,
        "İptal edildi" to R.string.cancelled,
        "İndirmeler" to R.string.downloads,
        "Sırada / hazırlanıyor" to R.string.queued_preparing,
        "İptal" to R.string.cancel_notification,
        "Kapak görseli gömülüyor" to R.string.embed_thumbnail_progress,
        "Medya bilgileri gömülüyor" to R.string.embed_metadata_progress,
        "Ses ve video birleştiriliyor" to R.string.merge_progress,
        "Dosya biçimi hazırlanıyor" to R.string.remux_progress,
        "Ses dosyası hazırlanıyor" to R.string.extract_audio_progress,
        "Aria2c yanıt vermedi; normal indirmeye geçiliyor" to R.string.aria_fallback_progress,
        "İndirme başlıyor" to R.string.starting,
        "İndiriliyor" to R.string.downloading,
        "Bu format kapağı gömmeyi desteklemiyor; kaynakta görsel varsa ayrı resim olarak kaydedilir." to R.string.thumbnail_unsupported,
        "Kaynakta kullanılabilir kapak bulunamadı; medya dosyası kaydedildi." to R.string.thumbnail_missing,
        "Dosya kaydedildi ancak bu formatta kapak gömülemedi." to R.string.thumbnail_not_embedded,
        "Kapak gömülemedi. Başka bir format seç veya kapağı ayrı kaydet." to R.string.thumbnail_error,
        "Kaynak erişimi reddetti. Bağlantıyı veya seçili oturumu kontrol et." to R.string.access_error,
        "Seçilen kalite veya biçim bu kaynakta bulunamadı." to R.string.format_error,
        "Medya dönüştürülemedi. Başka bir dosya biçimiyle tekrar dene." to R.string.convert_error,
        "İndirme tamamlanamadı. Bağlantıyı veya seçili oturumu kontrol et." to R.string.download_error,
        "Aria2c hazırlanamadı; normal indirme motoru kullanıldı." to R.string.aria_prepare_note,
        "Aria2c indirmesi tamamlanamadı; normal motorla yeniden denendi." to R.string.aria_retry_note,
        "Motoru hazırlamak için tekrar dene." to R.string.engine_prepare_retry,
        "Nightly güncellenemedi. Tekrar dene." to R.string.nightly_error,
        "Kararlı sürüm güncellenemedi. Tekrar dene." to R.string.stable_error,
        "İndirmeye hazır" to R.string.engine_ready,
        "Motor hazırlanıyor" to R.string.engine_preparing,
        "Güncellemeler kontrol ediliyor" to R.string.engine_checking,
        "Motor başlatılamadı" to R.string.engine_error,
        "Birlikte gelen sürüm" to R.string.bundled,
    )
    fun message(context: Context,value: String): String {
        legacy[value]?.let { return context.getString(it) }
        Regex("Yaklaşık (\\d+) dk (\\d+) sn").matchEntire(value)?.let {
            return context.getString(R.string.eta,it.groupValues[1],it.groupValues[2])
        }
        return value
    }
}
