package space.zenithw.app

object SettingsText {
    val labels=mapOf(
        "Abone / beğeni" to R.string.settings_extra_0,
        "Aralık, sıra ve hata davranışı" to R.string.settings_extra_1,
        "Arşiv" to R.string.settings_extra_2,
        "Ayarlara dön" to R.string.settings_extra_3,
        "Az veri" to R.string.settings_extra_4,
        "Açıklamayı kaydet" to R.string.settings_extra_5,
        "Açılışta otomatik güncelle" to R.string.settings_extra_6,
        "BAĞLANTI" to R.string.settings_extra_7,
        "Bağlantı hazırlanıyor" to R.string.settings_extra_8,
        "Bağlantı sayısı" to R.string.settings_extra_9,
        "Başlık + ID" to R.string.settings_extra_10,
        "Bilgi dosyasını kaydet" to R.string.settings_extra_11,
        "Bir video indirilemezse" to R.string.settings_extra_12,
        "Boş bölümler" to R.string.settings_extra_13,
        "Bölüm olarak işaretle" to R.string.settings_extra_14,
        "Cihazda saklanan çerezler" to R.string.settings_extra_15,
        "DASH / HLS paralel parçaları" to R.string.settings_extra_16,
        "DE + EN" to R.string.settings_extra_17,
        "Desteklenmeyen biçimlerde ayrı kapak kaydedilir." to R.string.settings_extra_18,
        "Devam et" to R.string.settings_extra_19,
        "Dil grubu" to R.string.settings_extra_20,
        "Dil, otomatik altyazı ve gömme" to R.string.settings_extra_21,
        "Dosya adı" to R.string.settings_extra_22,
        "Dosya adı, açıklama ve tekrarları atlama" to R.string.settings_extra_23,
        "Dosyalar ve arşiv" to R.string.settings_extra_24,
        "Download / Zenith" to R.string.settings_extra_25,
        "Dönüştürmeden önceki dosyaları da tutar." to R.string.settings_extra_26,
        "Eksik parçaları atla" to R.string.settings_extra_27,
        "Giriş" to R.string.settings_extra_28,
        "Güncelleniyor" to R.string.settings_extra_29,
        "Günlük" to R.string.settings_extra_30,
        "HTTP indirmelerinde kullanılır; sorun olursa normal motor denenir." to R.string.settings_extra_31,
        "Hangi bölümlere ne yapılacağını seç" to R.string.settings_extra_32,
        "Harici indirici ve bağlantı sayısı" to R.string.settings_extra_33,
        "Hazır profiller" to R.string.settings_extra_34,
        "Hazırlanıyor" to R.string.settings_extra_35,
        "Hız sınırı" to R.string.settings_extra_36,
        "Hız sınırı, ağ, denemeler ve bekleme" to R.string.settings_extra_37,
        "IP protokolü" to R.string.settings_extra_38,
        "Kalite, dosya biçimi, codec" to R.string.settings_extra_39,
        "Kanal + başlık" to R.string.settings_extra_40,
        "Kapak dosyası" to R.string.settings_extra_41,
        "Kapak görselini göm" to R.string.settings_extra_42,
        "Kapak, medya bilgisi ve bölümler" to R.string.settings_extra_43,
        "Kapalı" to R.string.settings_extra_44,
        "Kapanış" to R.string.settings_extra_45,
        "Karışık" to R.string.settings_extra_46,
        "Kaynak bağlantısını içerebilir." to R.string.settings_extra_47,
        "Kaynak dosyaları sakla" to R.string.settings_extra_48,
        "Kaynakta bölüm verisi varsa uygulanır." to R.string.settings_extra_49,
        "Kontrol ediliyor…" to R.string.settings_extra_50,
        "Liste aralığı" to R.string.settings_extra_51,
        "Liste indirmeye izin ver" to R.string.settings_extra_52,
        "Motor hazır" to R.string.settings_extra_53,
        "Motor sürümü doğrulanamadı. Tekrar dene." to R.string.settings_extra_54,
        "Motor ve indirme akışını izle" to R.string.settings_extra_55,
        "Motor ve indirme hareketleri burada görünür." to R.string.settings_extra_56,
        "Müzik" to R.string.settings_extra_57,
        "Müzik dışı" to R.string.settings_extra_58,
        "Otomatik altyazıları ekle" to R.string.settings_extra_59,
        "Otomatik güncelleme ve sürüm kanalı" to R.string.settings_extra_60,
        "Otomatik kaydedilir" to R.string.settings_extra_61,
        "Oynatma listeleri" to R.string.settings_extra_62,
        "Parça denemeleri" to R.string.settings_extra_63,
        "Profil seçimi mevcut varsayılanları değiştirir. Sonrasında tek tek düzenleyebilirsin." to R.string.settings_extra_64,
        "RU + EN" to R.string.settings_extra_65,
        "Ses dosyası" to R.string.settings_extra_66,
        "Ses kalitesi" to R.string.settings_extra_67,
        "Seçili bölümler" to R.string.settings_extra_68,
        "Seçimlerin sonraki indirmelerde hazır gelir. İndirme penceresinde yalnızca o dosya için değiştirebilirsin." to R.string.settings_extra_69,
        "Sonrakine geç" to R.string.settings_extra_70,
        "Sürüm kanalı" to R.string.settings_extra_71,
        "Sınırsız" to R.string.settings_extra_72,
        "TR + EN" to R.string.settings_extra_73,
        "Tamamlanan indirmeleri yerel arşivden kontrol eder." to R.string.settings_extra_74,
        "Tanıtım" to R.string.settings_extra_75,
        "Tarayıcı" to R.string.settings_extra_76,
        "Tarayıcı oturumları" to R.string.settings_extra_77,
        "Tarih + başlık" to R.string.settings_extra_78,
        "Tek dokunuşla günlük kullanım veya müzik" to R.string.settings_extra_79,
        "Tekrar denemeler" to R.string.settings_extra_80,
        "Tekrar indirilenleri atla" to R.string.settings_extra_81,
        "Tüm diller" to R.string.settings_extra_82,
        "Tümü" to R.string.settings_extra_83,
        "Uygulama dili" to R.string.settings_extra_84,
        "Varsayılan indirme" to R.string.settings_extra_85,
        "Video dosyası" to R.string.settings_extra_86,
        "Video kalitesi" to R.string.settings_extra_87,
        "Video ve ses" to R.string.settings_extra_88,
        "Videodan çıkar" to R.string.settings_extra_89,
        "Videoya göm" to R.string.settings_extra_90,
        "Yüksek kalite" to R.string.settings_extra_91,
        "Zaman aşımı" to R.string.settings_extra_92,
        "ZenithW files" to R.string.settings_extra_93,
        "sn" to R.string.settings_extra_94,
        "{count} kayıt · bu oturum" to R.string.settings_extra_95,
        "{name} profili uygulandı." to R.string.settings_extra_96,
        "Önizleme" to R.string.settings_extra_97,
        "İlk 10" to R.string.settings_extra_98,
        "İlk 100" to R.string.settings_extra_99,
        "İlk 25" to R.string.settings_extra_100,
        "İlk 5" to R.string.settings_extra_101,
        "İlk 50" to R.string.settings_extra_102,
        "İndirme sırası" to R.string.settings_extra_103,
        "İndirme öncesi bekleme" to R.string.settings_extra_104,
        "İndirmeyi bekletmeden arka planda kontrol eder." to R.string.settings_extra_105,
        "İşlem günlüğü" to R.string.settings_extra_106,
        "İşlem günlüğü. Bağlantılar gizlenir; burada komut yazılmaz." to R.string.settings_extra_107,
        "Şimdi güncelle" to R.string.settings_extra_108,
    )
}
